version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d movies_database -U app"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - django_docker_compose

  movies_admin:
    build: movies_admin
    ports:
      - "8000:8000"
    command: sh ./entrypoint.sh
    environment:
      - DB_HOST=postgres
      - DB_NAME=movies_database
      - DB_USER=app
      - DB_PASSWORD=123qwe
      - DB_PORT=5432
      - SECRET_KEY="django-insecure-*8c#*=7ih5!gjnb%51-0a-ovlra!33plexywzkp617p$qreawt"
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_EMAIL=admin@test.ru
      - SUPERUSER_PASSWORD=admin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - django_docker_compose
    volumes:
      - ./movies_admin:/opt/app
      - static-data:/var/www/static
      - media-data:/var/www/media

  nginx:
    image: nginx:1.25.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static-data:/var/www/static
      - media-data:/var/www/media
    depends_on:
      - movies_admin
    ports:
      - "80:80" 
    networks:
      - django_docker_compose

volumes:
  static-data:
    driver: local
  media-data:
    driver: local

networks:
  django_docker_compose:
    driver: bridge